/:
  controller: Base
  action: index

/mon-portfolio:
  controller: Base
  action: portfolio

/contact:
  controller: Base
  action: contact

/SAV:
  controller: Base
  action: contact

/login:
  controller: Auth
  action: login

/logout:
    controller: Auth
    action: logout

/register:
  controller: Auth
  action: register